version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql_db
    networks:
      - minha-rede
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  mysql_db:
    image: mysql/mysql-server:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: "%"
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  db_data: